### ISSUE TITLE
Improvements for `polars` query

### ISSUE THREAD

**Issue by etiennebacher** [jrosell/1br#1]
Hi, I came across this repo a bit randomly and I noticed the relatively poor performance of `polars` (the R package). It looks like the timing includes reading the data with `data.table`, converting to a polars `DataFrame` and then doing the aggregation. 

https://github.com/jrosell/1br/blob/26aab1d83249a48f540e2792f05c1490a2d48f68/run.R#L149-L165

This doesn't take advantage of the lazy API of `polars`. A more classic `polars` query would be 

```r
df <- pl$scan_csv(file_name)$
  group_by("state")$
  agg(
    pl$col("measurement")$min()$alias("min_m"),
    pl$col("measurement")$max()$alias("max_m"), # nolint: indentation_linter, line_length_linter.
    pl$col("measurement")$mean()$alias("mean_m")
  )$
  collect()

df <- NULL
gc()
```
I didn't run this locally but I'd expect important perf improvements.

Cheers

**Comment by jrosell** [comment]
Thanks, I could try it.

**Comment by jrosell** [comment]
I've just updated the results. I'm a bit suprised that polars could be better than duckdb. Is there a way to control the used cores? I have more than 8 cores and the solution should only use 8 cores.

**Comment by etiennebacher** [comment]
> I'm a bit suprised that polars could be better than duckdb

I'm not surprised, `polars` and `duckdb` are very close in many of the [DuckDb benchmarks](https://duckdblabs.github.io/db-benchmark/). In this case, maybe it depends on the benchmark, or the environment in which you run, if there are other processes working at the same time, etc.

> Is there a way to control the used cores?

Yes you can customize the number of threads used with the envvar `POLARS_MAX_THREADS`. Note that it has to be set *before* calling any `polars` function:

``` r
library(polars)
Sys.setenv(POLARS_MAX_THREADS = 2)

pl$thread_pool_size()
#> [1] 2
```

**Comment by etiennebacher** [comment]
Closing since the benchmark have been updated, thanks for the quick answer

**Comment by jrosell** [comment]
I need to test this more carefully. I need to be sure that caching is not a benchmarking issue and limit it to 8 threads.

**Comment by jrosell** [comment]
If I haven't done anything wrong, that doesn't seem to be the case. Limiting threads to 8 and generating the file each time doesn't seem to have a negative effect.
